services:
  - type: web
    name: mediamtx
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    ports:
      - 1935   # RTMP ingest
      - 8888   # HLS streaming
      - 8889   # WebRTC streaming
